BlogDog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^post/',include('posts.urls')),
    url(r'^admin/', admin.site.urls),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name='posts'

urlpatterns=[
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'add/$', views.PostCreate.as_view(), name='post-add'),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Post(models.Model):
	title=models.CharField(max_length=120)
	content=models.TextField()
	updated=models.DateTimeField(auto_now=True,auto_now_add=False)
	timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:detail', kwargs={'pk':self.pk})

posts/views.py
from django.views import generic
from .models import Post
from django.views.generic.edit import CreateView,UpdateView,DeleteView

class IndexView(generic.ListView):
    template_name='posts/index.html'

    def get_queryset(self):
    	return Post.objects.all()

class DetailView(generic.DetailView):
	model=Post
	template_name='posts/detail.html'

class PostCreate(CreateView):
	model=Post
	fields=['title','content']
    
 


posts/templates/posts/base.html
<!DOCTYPE html>
<html>
<head>
    {%load staticfiles%}
    <link rel="stylesheet" type="text/css" href="{%static 'posts/css/bootstrap.min.css'%}"/>
    <link rel="stylesheet" type="text/css" href="{%static 'posts/css/head.css'%}"/>
	<title>{%block title%}Posts{%endblock%}</title>
	
    
</head>
<body>
<!--<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
		      <a class="navbar-brand" href="{%url 'posts:index'%}">BlogDog</a>
		</div>
		<div>
			<ul  class="nav navbar-nav">
			    <li><a href="{%url 'posts:post-add'%}">Add a new post</a></li>
			</ul>
		</div>
	</div>
</nav>   -->
{%block body%}
{%endblock%}
<!--</body>
</html>
<button type="button" class="btn btn-default">
	<a class="navbar-brand" href="{%url 'posts:index'%}">BlogDog</a>
</button> 
<button type="button" class="btn btn-default">
    <a href="{%url 'posts:post-add'%}">Add a new post</a>
 </button>-->

posts/templates/posts/detail.html
{%extends 'posts/base.html'%}
{%block title%}Post Detail{%endblock%}
{%block body%}
<h3>{{post.title}} <small> {{post.timestamp}}</small></h3>
<br>
{{post.content}}
{%endblock%}

posts/templates/posts/form-template.html
{%for field in form%}
	<span>{{field.errors}}</span><br>
	<label>{{field.label_tag}}</label>
	<label>{{field}}</label>
{%endfor%}

posts/templates/posts/index.html
{%extends 'posts/base.html'%}
{%block body%}
{%if object_list%}
 <!--  <div class="jumbotron head" style="min-height:70%">
    <div style="text-align:center">
        <h2>THE GNU LINUX USERS GROUP</h2>
        <h3>Our projects</h3>
        <button type="button" class="btn btn-default">
            <a href="{%url 'posts:index'%}">BlogDog</a>
        </button> 
        <button type="button" class="btn btn-default">
            <a href="{%url 'posts:post-add'%}">Add a new post</a>
        </button>
    </div>
    </div> -->
    <div class="mainimg">
    {%load staticfiles%}
    <img class="myimg" src="{%static 'posts/images/mainimg.png'%}"/>
    <div class="container">
        <ul>
            <li><a class="linkhead1" style="color:white" href="{%url 'posts:index'%}">BlogDog</a></li>
            <li><a class="linkhead2" style="color:white" href="{%url 'posts:post-add'%}">Add a new post</a></li>            
        </ul>
    </div>
    <h1 class="txtinimg">THE GNU LINUX USERS GROUP</h1>
    </div>
	<div class="row">
    {%for post in object_list%}
    <div class="col-sm-12 col-md-6 jumbotron elements">
    <div class="container">
	<h3><a href="{%url 'posts:detail' post.id%}">{{post.title}}</a></h3>
    <h4>{{post.content}}</h4><br>
    {{post.updated}}<br>
    </div>
    </div>
    {%endfor%}
    </div>

{%else%}
    <h2>Hey add something</h2>
{%endif%}
{%endblock%}

posts/templates/posts/post_form.html
{%extends 'posts/base.html'%}
{%block title%}Add a new post{%endblock%}
{%block body%}
<form method="post" action="">
	{%csrf_token%}
	{%include 'posts/form-template.html'%}
	<button type="submit">Submit</button>
</form>
{%endblock%}